name: Build and Deploy
on:
  # Triggers the workflow on push to matching branches
  push:
    branches:
      - v2-staging-backend-checks
      - staging
      - master
      - V2
      - V2-staging
env:
  duplo_host: https://keyring.duplocloud.net
  duplo_token: "${{ secrets.DUPLO_SECRET }}"
  SERVICE_NAME: core                      
  TENANT_NAME: dev01
  CONTRACT_BUCKET: duploservices-dev01-contracts-178195871625                            

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# dummy commit 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set up for docker build
      - name: Get AWS credentials
        uses: duplocloud/ghactions-aws-jit@master
        with:
          tenant: ${{ env.TENANT_NAME }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push the docker image
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/demodata.Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # generates ABIs and byte-codes 
      - uses: addnab/docker-run-action@v3
        with:
          image: "${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          options: "-v ${{ github.workspace }}/generated-contracts:/app/artifacts/contracts"
          shell: bash
          run: /app/bin/entrypoint.sh
      - name: listing generated contracts and publish to S3
        run: |-
          # listing generated contracts
          ls -lrt "${{ github.workspace }}/generated-contracts"
          aws s3 cp --recursive "${{ github.workspace }}/generated-contracts" s3://$CONTRACT_BUCKET/$GITHUB_SHA
        # This part is important - it will be used by the deploy job
    outputs:
      image: "${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
