name: Build and Deploy
on:
  # Triggers the workflow on push to matching branches
  push:
    branches:
      - feature/duplo-devops
env:
  duplo_host: https://keyring.duplocloud.net
  duplo_token: "${{ secrets.DUPLO_SECRET }}"
  SERVICE_NAME: core                      
  TENANT_NAME: dev01                             

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set up for docker build
      - name: Get AWS credentials
        uses: duplocloud/ghactions-aws-jit@master
        with:
          tenant: ${{ env.TENANT_NAME }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push the docker image
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/demodata.Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        # This part is important - it will be used by the deploy job
    outputs:
      image: "${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

  container-test-job:
    runs-on: ubuntu-latest
    needs:
      - build
    container:
      image: "${{ needs.build.outputs.image }}"
      env:
        foo: bar
      volumes:
        - "${{ github.workspace }}/generated-contracts:/app/artifacts/contracts"
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
            
  publish:
    runs-on: ubuntu-latest
    needs:
      - container-test-job
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      # Set up for docker build
      - name: Get AWS credentials
        uses: duplocloud/ghactions-aws-jit@master
        with:
          tenant: ${{ env.TENANT_NAME }}

      - name: listing generated contracts
        run: |-
          # listing generated contracts
          ls -lrt "${{ github.workspace }}/generated-contracts"